# Generated by Django 6.0.4 on 2026-04-11 09:51
from django.db import migrations


def seed_permissions(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')

    app_label = 'inventory'

    # Define ALL permissions explicitly (IMPORTANT: no guessing)
    PERMISSIONS = {
        'product': [
            ('add_product', 'Can add product'),
            ('change_product', 'Can change product'),
            ('delete_product', 'Can delete product'),
            ('view_product', 'Can view product'),
        ],
        'inventoryrequest': [
            ('add_inventoryrequest', 'Can add inventory request'),
            ('change_inventoryrequest', 'Can change inventory request'),
            ('delete_inventoryrequest', 'Can delete inventory request'),
            ('view_inventoryrequest', 'Can view inventory request'),
            ('approve_inventoryrequest', 'Can approve inventory request'),
        ],
        'procurementrequest': [
            ('add_procurementrequest', 'Can add procurement request'),
            ('change_procurementrequest', 'Can change procurement request'),
            ('delete_procurementrequest', 'Can delete procurement request'),
            ('view_procurementrequest', 'Can view procurement request'),
            ('approve_procurementrequest', 'Can approve procurement request'),
        ],
        'inventorytransaction': [
            ('add_inventorytransaction', 'Can add inventory transaction'),
            ('change_inventorytransaction', 'Can change inventory transaction'),
            ('delete_inventorytransaction', 'Can delete inventory transaction'),
            ('view_inventorytransaction', 'Can view inventory transaction'),
        ],
    }

    for model, perms in PERMISSIONS.items():

        # Ensure content type exists
        ct, _ = ContentType.objects.get_or_create(
            app_label=app_label,
            model=model
        )

        for codename, name in perms:
            Permission.objects.get_or_create(
                codename=codename,
                content_type=ct,
                defaults={'name': name}
            )


def reverse_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')

    codenames = [
        'add_product', 'change_product', 'delete_product', 'view_product',

        'add_inventoryrequest', 'change_inventoryrequest',
        'delete_inventoryrequest', 'view_inventoryrequest',
        'approve_inventoryrequest',

        'add_procurementrequest', 'change_procurementrequest',
        'delete_procurementrequest', 'view_procurementrequest',
        'approve_procurementrequest',

        'add_inventorytransaction', 'change_inventorytransaction',
        'delete_inventorytransaction', 'view_inventorytransaction',
    ]

    Permission.objects.filter(codename__in=codenames).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(seed_permissions, reverse_permissions),
    ]
