# Generated by Django 6.0.4 on 2026-04-11 09:11
import random

from django.db import migrations, models


def seed_products(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')

    Product.objects.all().delete()

    stationery = [
        "pen", "pencil", "eraser", "notebook", "binder", "stapler",
        "paper clip", "marker", "highlighter", "ruler", "calculator",
        "scissors", "tape", "glue stick", "envelope", "folder",
        "sticky notes", "whiteboard marker", "clipboard", "puncher",
        "ink cartridge", "printer paper", "label paper", "carbon paper",
        "correction fluid", "sharpener", "book cover", "index card"
    ]

    office_supply = [
        "desk organizer", "file cabinet", "office chair", "desk lamp",
        "monitor stand", "keyboard", "mouse", "USB drive", "external HDD",
        "printer", "scanner", "shredder", "desk mat", "waste bin",
        "whiteboard", "pin board", "document tray", "laptop stand",
        "extension cable", "calculator desk"
    ]

    prefixes = ["A+", "Pro", "Eco", "Max", "Ultra", "Smart", "Basic", "Office", "ProLine"]

    created = 0
    for _ in range(200):
        base = random.choice([stationery, office_supply])
        name = f"{random.choice(prefixes)} {random.choice(base)}".upper()
        stock = random.randint(0, 100)

        obj, was_created = Product.objects.get_or_create(
            name=name,
            defaults={"stock": stock}
        )

        if was_created:
            created += 1

    print(f"Created {created} products")


def unseed_products(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Product.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0004_add_unique_constraint_to_product_name'),
    ]

    operations = [
        migrations.RunPython(seed_products, unseed_products),
    ]
