# Generated by Django 6.0.4 on 2026-04-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_seed_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
