# Generated by Django 6.0.4 on 2026-04-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_manager_view_inventorytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Received')], default='PENDING', max_length=20),
        ),
    ]
