# Generated by Django 6.0.4 on 2026-04-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_procurementrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
